---
title: "Impact of Money Supply on Markets and Growth"
author: "Matthew Adams"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Set code chunk options
knitr::opts_chunk$set(echo = TRUE)

# Load and install packages
pacman::p_load(tidyverse, eFRED, lubridate, zoo, janitor)

# set key to pull data from FRED
api_key <- "21489194ba838be7e47627eb82142f3a"
set_fred_key(api_key)
```


```{r data prep}
# Identify series for analysis
money_supply <- fred(value = "WM2NS")  # Money Supply (monthly)
stocks <- fred(value = "SP500")  # Stock Market Growth (daily)
gdp <- fred(value = "GDP")  # GDP Growth (quarterly)
interest_rate <- fred(value = "FEDFUNDS")  # Federal Funds Interest Rates (monthly)
cpi <- fred(value = "CPIAUCSL") # Consumer Price Index for All Urban Consumers: All Items in U.S. City Average 

# Combine data
all_data <- bind_rows(
  money_supply %>% as_tibble() %>% rename(Money = value),
  stocks %>% as_tibble() %>% rename(SP500 = value),
  gdp %>% as_tibble() %>% rename(GDP = value),
  interest_rate %>% as_tibble() %>% rename(FEDFUNDS = value)
)

# Convert date to a consistent format
all_data$date <- as.Date(all_data$date)

# Fill missing values using last observation carried forward
all_data_filled <- all_data %>%
  arrange(date) %>%
  group_by_all() %>%
  fill(everything()) %>%
  clean_names() %>% 
  pivot_longer(cols = 2:5, names_to = "names", values_to = "values") %>% 
  arrange(names) %>% 
  group_by(names) %>% 
  mutate(norm_value = scale(values)) %>% 
  ungroup() %>% 
  na.omit(norm_value) %>% 
  filter(names != "fedfunds") %>% 
  filter(date > "2016-02-23")
```


```{r data filtering}
reference_date <- as.Date("2020-02-24")

pre_data <- all_data_filled %>% 
  mutate(days_since_reference = as.numeric(date - reference_date)) %>%
  filter(days_since_reference < 0) %>%
  group_by(names) %>%
  mutate(growth = ((last(values) - first(values)) / first(values)))

post_data <- all_data_filled %>% 
  mutate(days_since_reference = as.numeric(date - reference_date)) %>%
  filter(days_since_reference >= 0) %>%
  group_by(names) %>%
  mutate(growth = ((last(values) - first(values)) / first(values)))

```

```{r analysis}
# Combine pre and post data
combined_data <- bind_rows(
  pre_data %>% mutate(period = "pre_eventX"),
  post_data %>% mutate(period = "post_eventX")
)

# Plotting
ggplot(combined_data, aes(x = date, y = norm_value, color = names)) +
  geom_line(linewidth = 1) +
  facet_grid(period ~ ., scales = "free", switch = "x") +
  labs(title = "Normalized Values - Pre and Post COVID",
       x = "Date",
       y = "Normalized Value",
       color = "Series")
```

```{r analysis 2}
# Reorder levels in the 'period' variable
combined_data$period <- factor(combined_data$period, levels = c("pre_eventX", "post_eventX"))

# Plotting
ggplot(combined_data, aes(x = names, y = growth, fill = period)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.7) +
  labs(title = "Growth Percentage - Pre and Post COVID",
       x = "Series",
       y = "Growth Percentage",
       fill = "Period") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_manual(values = c("pre_eventX" = "lightblue", "post_eventX" = "lightgreen"))

```

```{r correlation 1}
qrtly_gdp <- gdp %>% 
  group_by(quarter = zoo::as.yearqtr(date)) %>% 
  filter(quarter > "1974 Q4") %>% 
  select(-date)

qrtly_money_supply <- money_supply %>% 
  group_by(quarter = zoo::as.yearqtr(date)) %>% 
  summarise(value = mean(value, na.rm = TRUE)) %>% 
  filter(quarter < "2024 Q1")

c <- cor.test(qrtly_gdp$value, qrtly_money_supply$value) %>% print()


merged <- merge(qrtly_gdp, qrtly_money_supply, by = "quarter")

# Plotting with ggplot2 and adding a line of best fit
ggplot(merged, aes(x = value.x, y = value.y)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  # Adding a linear regression line
  labs(title = "Correlation Between Money Supply & GDP from 1975 Q1- 2023 Q4",
       x = "Quarterly GDP",
       y = "Quarterly M1 Money Supply")

```

```{r correlation 2}
qrtly_stocks <- stocks %>% 
  group_by(quarter = zoo::as.yearqtr(date)) %>% 
  summarise(value = mean(value, na.rm = TRUE)) %>%
  filter(quarter > "1980 Q3") %>% 
  filter(quarter < "2024 Q1") %>% 
  na.omit()

qrtly_money_supply_v2 <- qrtly_money_supply %>% 
  filter(quarter >= "2014 Q1")

c2 <- cor.test(qrtly_stocks$value, qrtly_money_supply_v2$value) %>% print()


merged2 <- merge(qrtly_stocks, qrtly_money_supply_v2, by = "quarter")

# Plotting with ggplot2 and adding a line of best fit
ggplot(merged2, aes(x = value.x, y = value.y)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  # Adding a linear regression line
  labs(title = "Correlation Between Money Supply & S&P 500 from 2014 Q1- 2023 Q4",
       x = "Quarterly S&P 500",
       y = "Quarterly M1 Money Supply")

```

```{r analysis 3}
# Assuming 'value.x' and 'value.y' are the columns in your merged data frame
roc <- merged2 %>%
  mutate(roc_gdp = (value.x / lag(value.x) - 1) * 100,
         roc_m1 = (value.y / lag(value.y) - 1) * 100) %>% 
  select(quarter, roc_gdp, roc_m1) %>% 
  na.omit() %>% 
  filter(quarter > 2015-01-01)

# Visualization using ggplot2
ggplot(roc, aes(x = quarter)) +
  geom_line(aes(y = roc_gdp, color = "GDP Rate of Change"), size = .8) +
  geom_line(aes(y = roc_m1, color = "M1 Rate of Change"), size = .8) +
  labs(title = "Quarterly Rate of Change Comparison",
       y = "Rate of Change (%)",
       x = "Quarter")
```

```{r analysis 4}
cpi_filtered <- cpi %>% 
  mutate(year = year(date)) %>% 
  mutate(month = month(date)) %>%
  mutate(day = day(date)) %>% 
  filter(year >= "1975") %>% 
  select(value, year, month) %>% 
  rename(cpi = value) %>% 
  unite(year, month, col = "period", sep = "-")

money_supply_filtered <- money_supply %>% 
  mutate(year = year(date)) %>% 
  mutate(month = month(date)) %>%
  mutate(day = day(date)) %>% 
  unite(year, month, col = "period", sep = "-") %>% 
  select(-day) %>%
  rename(m2 = value)

df <- money_supply_filtered %>% 
  left_join(cpi_filtered, by = "period") %>% 
  relocate(period, .before = m2) %>% 
  mutate(date = as_date(date))

df_long <- df %>% 
  pivot_longer(cols = c(3:4), names_to = "series", values_to = "value") %>% 
  group_by(series) %>% 
  mutate(norm_value = scale(value))

df_filtered <- df %>% 
  filter(period >= "2019-1")

df_long_filtered <- df_filtered %>% 
  pivot_longer(cols = c(3:4), names_to = "series", values_to = "value") %>% 
  group_by(series) %>% 
  mutate(norm_value = scale(value))

delta <- df_long_filtered %>% 
  arrange(desc(date)) %>% 
  summarise(cpi_delta = (((first(cpi)-last(cpi))/last(cpi))*100),
            m2_delta = (((first(m2)-last(m2))/last(m2))*100)
            )

cpi_delta <- delta$cpi_delta
m2_delta <- delta$m2_delta
```

```{r plotting}
# first case of covid in USA
# cares act signed into law - $2.2 trillion stimulus package
# ppp loan applications begin - $798 billion total loans
# consolidated appropriations act - $900 billion additional stimulus funding
# american rescue plan - $1.9 trillion relief package

# Main plot
historical_plot <- ggplot(df_long, aes(x = date, y = norm_value, group = series, color = series)) +
  geom_line(linewidth = 1) +
  labs(
    x = "Period",                
    y = "Normalized Value",     
    title = "Historical Relationship Between Money Supply and Inflation",
    color = ""
  ) +
  scale_x_date(date_breaks = "5 years", date_minor_breaks = "1 year", date_labels = "%Y") +
  theme_minimal() +          
  theme(                     
    legend.position = "top", 
    plot.title = element_text(face = "bold"),
    plot.margin = margin(t = 20, r = 20, b = 20, l = 20)
  ) +
  labs(caption = "Data Source: FRED")

historical_plot

label_data <- data.frame(
  date = as.Date(c("2020-01-20", "2020-03-27", "2020-04-06", "2020-12-21", "2021-03-11")),
  label = c("First COVID Case", "CARES Act", "PPP Loan Inception", 
            "Consolidated Appropriations Act", "American Rescue Plan"),
  color = c("red", "blue", "green", "orange", "purple")
)

# Custom color scale for the vertical lines and series
line_colors <- setNames(label_data$color, label_data$label)
series_colors <- c("cpi" = "brown", "m2" = "darkcyan")

# Combine both color mappings
all_colors <- c(series_colors, line_colors)

# Main plot
main_plot <- ggplot(df_long_filtered, aes(x = date, y = norm_value, group = series, color = series)) +
  geom_line(linewidth = 1) +
  labs(
    x = "Period",                
    y = "Normalized Value",     
    title = "Analysis of Fiscal Policy in Response to COVID Pandemic",   
    color = "Legend"            
  ) +
  scale_x_date(date_breaks = "1 years", date_minor_breaks = "1 month", date_labels = "%Y") +
  theme_minimal() +          
  theme(                     
    legend.position = "top", 
    plot.title = element_text(face = "bold"),
    plot.margin = margin(t = 20, r = 20, b = 20, l = 20)
  ) +
  labs(caption = "Data Source: FRED") +
  geom_vline(data = label_data, aes(xintercept = as.numeric(date), color = label), linetype = "solid") +
  scale_color_manual(values = all_colors) +
  guides(color = guide_legend(title.position = "top", title.hjust = 0.5))

main_plot

```

```{r animated}
library(gganimate)

animated_plot <- df_filtered %>%
  ggplot(aes(x = date, y = norm_value, group = series, color = series)) +
  geom_line() +
  geom_smooth(method = "loess", se = FALSE) +  # Add smoothed lines
  labs(x = "Period", y = "Normalized Value", title = "Relationship of CPI and M2 Time: {frame_along}") +
  transition_reveal(date) + 
  view_follow(fixed_y = TRUE) + 
  ease_aes("linear")

animate(animated_plot, end_pause = 50, width = 700)
```

```{r correlation 4}

cor_test <- cor(df$cpi, df$m2) %>% 
  print()

cor_plot <- ggplot(df, aes(x = cpi, y = m2)) + 
  geom_point(color = "blue", size = 2) +  # Customize points
  geom_smooth(method = "lm", se = FALSE, color = "red") +  # Add line of best fit
  labs(x = "Consumer Price Index (CPI)", y = "Money Supply (M2)",  # Label axes
       title = "Scatter Plot with Line of Best Fit") +  # Add title
  theme_minimal()

cor_plot

# Simple linear regression
model <- lm(cpi ~ m2, data = df)
summary(model)

```

```{r granger test}
library(lmtest)

# Perform Granger causality test
granger_test <- grangertest(df$cpi ~ df$m2, order = 1)
print(granger_test)
```



```
