---
title: "Analysis"
author: "Matthew Adams"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
pacman::p_load(tidyverse, ggplot2, eFRED, zoo)

api_key <- "21489194ba838be7e47627eb82142f3a"
set_fred_key(api_key)
```

Pull FRED data series
```{r }
debt <- fred("TOTALSL")
default <- fred("DRCCLACBS")
interest <- fred("DFF")
```

Align time frequency
```{r }
debt_quarterly <- debt %>%
  mutate(date = as.Date(date)) %>%
  group_by(quarter = zoo::as.yearqtr(date)) %>%
  summarise(TOTALSL = mean(TOTALSL, na.rm = TRUE))

interest_quarterly <- interest %>%
  mutate(date = as.Date(date)) %>%
  group_by(quarter = zoo::as.yearqtr(date)) %>%
  summarise(DFF = mean(DFF, na.rm = TRUE))

default_quarterly <- default %>%
  mutate(date = as.Date(date)) %>%
  group_by(quarter = zoo::as.yearqtr(date)) %>%
  summarise(DRCCLACBS = sum(DRCCLACBS, na.rm = TRUE))

merged_data <- merge(debt_quarterly, default_quarterly, by = "quarter")
merged_data <- merge(merged_data, interest_quarterly, by = "quarter")

merged_data <- merged_data %>%
  mutate(normalized_default_rate = (DRCCLACBS / TOTALSL)*100) %>% 
  mutate(debt_norm = ifelse(is.na(TOTALSL), NA, round((TOTALSL / max(TOTALSL, na.rm = TRUE)), 2))) %>% 
  mutate(default_norm = ifelse(is.na(DRCCLACBS), NA, round((DRCCLACBS / max(DRCCLACBS, na.rm = TRUE)), 2))) %>% 
  mutate(interest_norm = ifelse(is.na(DFF), NA, round((DFF / max(DFF, na.rm = TRUE)), 2))) %>% 
  mutate(ndr_norm = ifelse(is.na(normalized_default_rate), NA, round((normalized_default_rate / max(normalized_default_rate, na.rm = TRUE)), 2)))

```

Plot normalized
```{r }
# Convert quarter to Date class for better handling
merged_data$quarter <- as.Date(as.yearqtr(merged_data$quarter), frac = 1)

ggplot(merged_data, aes(x = quarter)) +
  geom_line(aes(y = debt_norm, color = "Credit Card Debt"), size = 1) +
  geom_line(aes(y = default_norm, color = "Default Rate"), size = 1) +
  geom_line(aes(y = interest_norm, color = "Interest Rate"), size = 1) +
  geom_line(aes(y = ndr_norm, color = "Default Rate/ CC Debt"), size = 1) +
  
  # Customize labels and titles
  labs(title = "Analysis of American Consumer Credit Health",
       y = "Normalized Values",
       x = "Quarter") +
  
  # Customize colors and legend labels
  scale_color_manual(name = "",
                     values = c("Credit Card Debt" = "purple", 
                                "Default Rate" = "navy",
                                "Interest Rate" = "blue",
                                "Default Rate/ CC Debt" = "orange"),
                     labels = c("Credit Card Debt", 
                                "Default Rate",
                                "Interest Rate",
                                "Default Rate/ CC Debt"),
                     breaks = c("Credit Card Debt", "Default Rate", "Interest Rate", "Default Rate/ CC Debt")) +
  
  # Adjust x-axis ticks and labels
  scale_x_date(date_breaks = "3 year", date_labels = "%Y") +
  
  # Add legend
  theme(legend.position = "top",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8),
        legend.box.margin = margin(6, 6, 6, 6)) +
  
# Add source annotation
  annotate("text", x = max(merged_data$quarter), y = Inf, hjust = 1.1, vjust = 1.1,
           label = "Source: FRED", size = 3.5, color = "black", parse = TRUE)
```

```{r}

```


