---
title: "Cross-Correlation Function Work"
author: "Matthew Adams"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(eFRED)
library(memoise)

api_key <- "21489194ba838be7e47627eb82142f3a"
set_fred_key(api_key)
```

```{r Series List}
series_list <- list(
  yield_curve            = list(value = "T10Y2YM"),
  
  # Jobs
  payroll                = list(value = "PAYEMS"),
  unemployment           = list(value = "UNRATE"),
  
  # Fiscal aggregates
  total_debt             = list(value = "GFDEBTN"),
  federal_deficit        = list(value = "FYFSD"),
  interest_payments      = list(value = "A091RC1Q027SBEA"),
  
  # Output
  gdp                    = list(value = "GDP"),
  
  # Inflation measures
  cpi                    = list(value = "CPIAUCSL"),
  core_cpi               = list(value = "CPILFESL"),
  pce_price              = list(value = "PCEPI"),
  pce_ex_food_energy     = list(value = "PCEPILFE"),
  
  # Money aggregates
  m2                     = list(value = "M2SL"),
  real_m2                = list(value = "M2REAL"),
  
  # Fed policy and balance sheet
  interest_rate          = list(value = "DFF"),
  fed_assets             = list(value = "WALCL")
)

series_meta <- tibble(
  series_id   = names(series_list),
  series_code = map_chr(series_list, "value"),
  series_name = c(
    "10Y–2Y Yield Curve",
    "Nonfarm Payroll",
    "Unemployment Rate",
    "Total Public Debt",
    "Federal Surplus/Deficit",
    "Federal Interest Payments",
    "Nominal GDP",
    "Headline CPI",
    "Core CPI",
    "PCE Price Index",
    "Core PCE",
    "M2 Money Stock",
    "Real M2",
    "Effective Fed Funds Rate",
    "Fed Total Assets"
  )
)
```

```{r Pull FRED Data}
fred_cached <- memoise(function(series_code) {
  fred(series = series_code, all = FALSE) %>% as_tibble()
})

df <- series_meta %>% 
  mutate(
    raw = map(
      series_code,
      ~ fred_cached(.x) %>% as_tibble()
    )
  ) %>% 
  unnest(raw) %>%   
  arrange(series_id) %>% 
  filter(!is.na(series))
```

```{r}
standardize <- function(x) {
  (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)
}

df <- df %>%
  group_by(series_name) %>%
  mutate(
    series_std = standardize(series)
  ) %>%
  ungroup()
```

```{r }
lag_series1 <- "m2"
lag_series2 <- "cpi"

y1 <- df %>%
  filter(series_name == lag_series1) %>%
  arrange(date) %>%
  pull(series_std)

y2 <- df %>%
  filter(series_name == lag_series2) %>%
  arrange(date) %>%
  pull(series_std)

cc <- ccf(y1, y2, plot = FALSE, lag.max = 12)

cc_tbl <- tibble(
  lag = as.integer(cc$lag),
  acf = as.numeric(cc$acf)
)
```

```{r }



```

```{r }
lag_max <- 4
lag_series1 <- 
lag_series2 <- 

y1 <- df %>% filter(series_name == lag_series1) %>% arrange(date) %>% pull(value_norm)
y2 <- df %>% filter(series_name == lag_series2) %>% arrange(date) %>% pull(value_norm)
cc <- ccf(y1, y2, plot = FALSE, lag.max = lag_max)
fn
tibble(lag = as.integer(cc$lag), acf = as.numeric(cc$acf))


```
