---
title: "Economic Statistal Analysis"
author: "Matthew Adams"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(eFRED)
library(memoise)
library(scales)

api_key <- "21489194ba838be7e47627eb82142f3a"
set_fred_key(api_key)
```

```{r Series List}
series_list <- list(
  # Recession Indicators
  sahm_rule              = list(value = "SAHMREALTIME"),
  smoothed_prob   = list(value = "RECPROUSM156N"),
  gdp_based              = list(value = "JHGDPBRINDX"),
  yield_curve            = list(value = "T10Y2YM"),
  
  # Jobs
  payroll                = list(value = "PAYEMS"),
  unemployment           = list(value = "UNRATE"),
  
  # Fiscal aggregates
  total_debt             = list(value = "GFDEBTN"),
  federal_deficit        = list(value = "FYFSD"),
  interest_payments      = list(value = "A091RC1Q027SBEA"),
  
  # Output
  gdp                    = list(value = "GDP"),
  
  # Inflation measures
  cpi                    = list(value = "CPIAUCSL"),
  core_cpi               = list(value = "CPILFESL"),
  pce_price              = list(value = "PCEPI"),
  pce_ex_food_energy     = list(value = "PCEPILFE"),
  
  # Money aggregates
  m2                     = list(value = "M2SL"),
  real_m2                = list(value = "M2REAL"),
  
  # Fed policy and balance sheet
  interest_rate          = list(value = "DFF"),
  fed_assets             = list(value = "WALCL")
)

series_meta <- tibble(
  series_id   = names(series_list),
  series_code = map_chr(series_list, "value"),
  series_name = c(
    "Sahm Rule",
    "Smoothed Probability",
    "GDP Based",
    "10Y–2Y Yield Curve",
    "Nonfarm Payroll",
    "Unemployment Rate",
    "Total Public Debt",
    "Federal Surplus/Deficit",
    "Federal Interest Payments",
    "Nominal GDP",
    "Headline CPI",
    "Core CPI",
    "PCE Price Index",
    "Core PCE",
    "M2 Money Stock",
    "Real M2",
    "Effective Fed Funds Rate",
    "Fed Total Assets"
  )
)
```

```{r Pull FRED Data}
fred_cached <- memoise(function(series_code) {
  fred(series = series_code, all = FALSE) %>% as_tibble()
})

df <- series_meta %>% 
  mutate(
    raw = map(
      series_code,
      ~ fred_cached(.x) %>% as_tibble()
    )
  ) %>% 
  unnest(raw) %>%   
  arrange(series_id) %>% 
  filter(!is.na(series))

df %>% 
  filter(if_any(everything(), is.na))

df %>% 
  filter(
    series_id %in% c("gdp_based", "smoothed_prob", "sahm_rule", "yield_curve")
    # date > "2000-01-01"
    ) %>% 
  ggplot(aes(x = date, y = series, group = series_id, color = series_id)) +
  geom_point() +
  geom_line()
```
```{r Preliminary Statistics}
s <- df %>% 
  filter(series_id %in% c("gdp_based", "smoothed_prob", "sahm_rule", "yield_curve")) %>% 
  group_by(series_id) %>% 
  summarise(
    min = min(series),
    max = max(series)
  ) %>%
  print()


# scaled = (series - min(series, na.rm = TRUE)) / (max(series, na.rm = TRUE) - min(series, na.rm = TRUE))

rescaled <- df %>% 
  filter(series_id %in% c("gdp_based", "smoothed_prob", "sahm_rule", "yield_curve")) %>% 
  group_by(series_id) %>% 
  mutate(
    rescaled = rescale(series, c(0,1)),
    z_score = ((series - mean(series, na.rm = TRUE)) / sd(series, na.rm = TRUE))
  ) %>% 
  ungroup()

rescaled %>% 
  filter(date > "2000-01-01") %>% 
  ggplot(aes(x = date, y = z_score, group = series_id, color = series_id)) +
  geom_point() +
  geom_line()

```

```{r Dot Com Bust}
obs1_inversion <- as_date("2000-02-01")
obs1_resteepening <- as_date("2001-01-01")

rescaled %>% 
  filter(date >= "1999-01-01" & date <= "2003-01-01") %>% 
  ggplot(aes(x = date, y = z_score, color = series_name)) +
  geom_point() +
  geom_line() +
  labs(title = "Recession Indicators During Dot Cot Bust", x = "Date", y = "Z-Score") +
  geom_vline(xintercept = obs1_inversion, color = "navyblue", linetype = "dashed", size = .5, alpha = .7) +
  geom_vline(xintercept = obs1_resteepening, color = "blue", linetype = "dashed", size = .5, alpha = .7) +
  annotate("text", x = obs1_inversion, y = 1.2, label = "Inversion", color = "navyblue", angle = 90, vjust = -0.5) +
  annotate("text", x = obs1_resteepening, y = 1.2, label = "Resteepening", color = "blue", angle = 90, vjust = -0.5) +
  scale_color_brewer(palette = "Oranges") +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme_dark() +
  coord_cartesian(clip = "off") +
  theme(plot.margin = margin(t = 30, r = 20, b = 20, l = 20))

```


```{r Global Financial Crisis}
obs2_inversion <- as_date("2006-02-01")
obs2_resteepening <- as_date("2007-06-01")

rescaled %>% 
  filter(date >= "2005-01-01" & date <= "2010-01-01") %>% 
  ggplot(aes(x = date, y = z_score, color = series_name)) +
  geom_point() +
  geom_line() +
  labs(title = "Recession Indicators During Global Financial Crisis", x = "Date", y = "Z-Score") +
  geom_vline(xintercept = obs2_inversion, color = "navyblue", linetype = "dashed", size = .5, alpha = .7) +
  geom_vline(xintercept = obs2_resteepening, color = "blue", linetype = "dashed", size = .5, alpha = .7) +
  annotate("text", x = obs2_inversion, y = 2.2, label = "Inversion", color = "navyblue", angle = 90, vjust = -0.5) +
  annotate("text", x = obs2_resteepening, y = 2.2, label = "Resteepening", color = "blue", angle = 90, vjust = -0.5) +
  scale_color_brewer(palette = "Oranges") +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme_dark() +
  coord_cartesian(clip = "off") +
  theme(plot.margin = margin(t = 30, r = 20, b = 20, l = 20))
```
```{r Present}
obs3_inversion <- as_date("2022-07-01")
obs3_resteepening <- as_date("2024-09-01")

rescaled %>% 
  filter(date > "2021-01-01") %>%  
  ggplot(aes(x = date, y = z_score, color = series_name)) +
  geom_point() +
  geom_line() +
  labs(title = "Recession Indicators at Present", x = "Date", y = "Z-Score") +
  geom_vline(xintercept = obs3_inversion, color = "navyblue", linetype = "dashed", size = .5, alpha = .7) +
  geom_vline(xintercept = obs3_resteepening, color = "blue", linetype = "dashed", size = .5, alpha = .7) +
  annotate("text", x = obs3_inversion, y = 1.8, label = "Inversion", color = "navyblue", angle = 90, vjust = -0.5) +
  annotate("text", x = obs3_resteepening, y = 1.8, label = "Resteepening", color = "blue", angle = 90, vjust = -0.5) +
  scale_color_brewer(palette = "Oranges") +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  theme_dark() +
  coord_cartesian(clip = "off") +
  theme(plot.margin = margin(t = 30, r = 20, b = 20, l = 20))
```








```{r}
standardize <- function(x) {
  (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)
}

df <- df %>%
  group_by(series_name) %>%
  mutate(
    series_std = standardize(series)
  ) %>%
  ungroup()
```

```{r }
# pull NBER recession indicator (1 = in recession)
getSymbols("USREC", src = "FRED")    
recess <- data.frame(
  date = index(USREC),
  in_recession = as.numeric(coredata(USREC))
)

recess %>% filter(in_recession == 1) %>% arrange(desc(date))
```

```{r }
# pick your predictors
model_df <- df %>%
  filter(series_id %in% c("yield_curve", "unemployment", "m2", "fed_assets")) %>%
  select(series_id, date, series) %>%
  pivot_wider(names_from = series_id, values_from = series) %>%
  arrange(date) %>%
  # compute month-over-month changes
  mutate(
    uc_change = (unemployment - lag(unemployment)) * 100,    # percentage-point change
    m2_pct    = (m2 / lag(m2) - 1) * 100
  ) %>%
  left_join(recess, by = "date") %>%
  filter(if_all(everything(), ~ !is.na(.)))
```

```{r }
model <- glm(
  in_recession ~ yield_curve + uc_change,
  data = model_df,
  family = binomial()
)
```

```{r }
model_df <- model_df %>%
  mutate(
    recession_prob = predict(model, type = "response")
  )
```

```{r }
plot_ly(
  model_df,
  x = ~date,
  y = ~recession_prob,
  type = "scatter", mode = "lines",
  hoverinfo = "y+text",
  text = ~paste0("Risk: ", round(100*recession_prob,1), "%")
  ) %>%
  layout(
    title = "Predicted Recession Risk",
    yaxis = list(title = "Probability", tickformat = ".0%"),
    xaxis = list(title = "")
  )
```

```{r }
lag_series1 <- "m2"
lag_series2 <- "cpi"

y1 <- df %>%
  filter(series_id == lag_series1) %>%
  arrange(date) %>%
  pull(series_std)

y2 <- df %>%
  filter(series_id == lag_series2) %>%
  arrange(date) %>%
  pull(series_std)

cc <- ccf(y1, y2, plot = TRUE, lag.max = 12)

cc_tbl <- tibble(
  lag = as.integer(cc$lag),
  acf = as.numeric(cc$acf)
)
```

```{r }



```

```{r }


```
