---
title: "Recession Risk"
author: "Matthew Adams"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(quantmod)       # for getSymbols
library(dplyr)
library(lubridate)
```

```{r }
# pull NBER recession indicator (1 = in recession)
getSymbols("USREC", src = "FRED")    
recess <- data.frame(
  date = index(USREC),
  in_recession = as.numeric(coredata(USREC))
)
```

```{r }
# pick your predictors
model_df <- df %>%
  filter(series_id %in% c("yield_curve", "unemployment", "m2", "fed_assets")) %>%
  select(series_id, date, series) %>%
  pivot_wider(names_from = series_id, values_from = series) %>%
  arrange(date) %>%
  # compute month-over-month changes
  mutate(
    uc_change = (unemployment - lag(unemployment)) * 100,    # percentage-point change
    m2_pct    = (m2 / lag(m2) - 1) * 100
  ) %>%
  left_join(recess, by = "date") %>%
  filter(if_all(everything(), ~ !is.na(.)))
```

```{r }
model <- glm(
  in_recession ~ yield_curve + uc_change,
  data = model_df,
  family = binomial()
)
```

```{r }
model_df <- model_df %>%
  mutate(
    recession_prob = predict(model, type = "response")
  )
```

```{r }
plot_ly(
  model_df,
  x = ~date,
  y = ~recession_prob,
  type = "scatter", mode = "lines",
  hoverinfo = "y+text",
  text = ~paste0("Risk: ", round(100*recession_prob,1), "%")
  ) %>%
  layout(
    title = "Predicted Recession Risk",
    yaxis = list(title = "Probability", tickformat = ".0%"),
    xaxis = list(title = "")
  )
```

```{r }

```